name: Tests Back end

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # Aviso: Variáveis de ambiente expostas, use o GitHub Secrets!!!
    env:
      SECRET_KEY: "django-insecure-1234"
      DEBUG: False
      DATABASE_NAME: "postgres"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_HOST: "localhost"
      DATABASE_PORT: 5432


    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest